# We want OpenGL or OpenGLES2
# For ARM64, prefer EGL + GLESv2
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
  # Try EGL + GLES first for ARM
  find_package(EGL)
  if(EGL_FOUND)
    find_package(GLES2)
    if(GLES2_FOUND)
      message(STATUS "Using EGL + GLES2 for ARM64")
      set(OPENGL_LIBS GLESv2 EGL)
      add_definitions(-DUSE_EGL)
    else()
      message(STATUS "EGL found but GLES2 not found, trying desktop OpenGL")
      find_package(OpenGL)
      if(OPENGL_FOUND)
        set(OPENGL_LIBS ${OPENGL_gl_LIBRARY})
      else()
        message(FATAL_ERROR "OpenGL, GLES2, or EGL+GLES2 is required for ARM64")
      endif()
    endif()
  else()
    # No EGL, try GLES2 directly
    find_package(GLES2)
    if(GLES2_FOUND)
      message(STATUS "Using GLES2 directly (no EGL)")
      set(OPENGL_LIBS ${GLES2_LIBRARY})
    else()
      message(STATUS "No EGL/GLES2, trying desktop OpenGL")
      find_package(OpenGL)
      if(OPENGL_FOUND)
        set(OPENGL_LIBS ${OPENGL_gl_LIBRARY})
      else()
        message(FATAL_ERROR "OpenGL or GLES2 is required")
      endif()
    endif()
  endif()
else()
  # Desktop x86_64 build
  find_package(OpenGL)
  if(NOT OPENGL_FOUND)
    find_package(GLES2)
    if(NOT GLES2_FOUND)
      message(FATAL_ERROR "OpenGL or GLES2 is required")
    else()
      set(OPENGL_LIBS ${GLES2_LIBRARY})
    endif()
  else()
    set(OPENGL_LIBS ${OPENGL_gl_LIBRARY})
  endif()
endif()

find_package(MPV REQUIRED)
include_directories(${MPV_INCLUDE_DIR})

# ARM64-specific: check for V4L2 for hardware decoding
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
  find_package(V4L2)
  if(V4L2_FOUND)
    message(STATUS "V4L2 available for hardware video decoding")
    include_directories(${V4L2_INCLUDE_DIRS})
  endif()

  # Check for VAAPI
  find_package(VAAPI)
  if(VAAPI_FOUND)
    message(STATUS "VAAPI available for hardware video decoding")
    include_directories(${VAAPI_INCLUDE_DIRS})
  endif()
endif()
