// Autogenerated CPP file

#include <QString>
#include "Version.h"

QString Version::GetVersionString()
{
  return QString("2.0.0-dev");
}

QString Version::GetCanonicalVersionString()
{
  return QString("2.0.0");
}

QString Version::GetBuildDate()
{
  return QString("2026-01-02");
}

QString Version::GetWebVersion()
{
  return QString("");
}

QString Version::GetDependenciesVersion()
{
  return QString("");
}

QString Version::GetQtDepsVersion()
{
  return QString("");
}
